"use client";

import { motion } from "framer-motion";
import { CheckCircle2, Loader2, XCircle } from "lucide-react";
import { useTranslations } from "next-intl";
import { useEffect, useRef, useState } from "react";
import { checkNicknameAvailability } from "@/actions/profile";
import { CountrySelector } from "@/components/country-selector";
import { OnboardStepHeader } from "@/components/onboard-step-header";
import { DatePicker } from "@/components/ui/date-picker";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { generateNicknameFromName } from "@/schemas/profile";

interface BasicInfoStepProps {
  name: string;
  email: string;
  nickname?: string;
  dateOfBirth?: Date | null;
  nationality?: string;
  country?: string;
  city?: string;
  location?: string;
  autoFilledFields: {
    name?: boolean;
    email?: boolean;
  };
  onNameChange: (value: string) => void;
  onEmailChange: (value: string) => void;
  onNicknameChange: (value: string) => void;
  onDateOfBirthChange: (value: Date | null) => void;
  onNationalityChange: (value: string) => void;
  onCountryChange: (value: string) => void;
  onCityChange: (value: string) => void;
  onLocationChange: (value: string) => void;
}

export function BasicInfoStep({
  name,
  email,
  nickname = "",
  dateOfBirth,
  nationality = "",
  country = "",
  city = "",
  location = "",
  autoFilledFields,
  onNameChange,
  onEmailChange,
  onNicknameChange,
  onDateOfBirthChange,
  onNationalityChange,
  onCountryChange,
  onCityChange,
  onLocationChange,
}: BasicInfoStepProps) {
  const t = useTranslations("onboardingPage.steps.basicInfo");
  const [nicknameValue, setNicknameValue] = useState(nickname);
  const [isCheckingNickname, setIsCheckingNickname] = useState(false);
  const [nicknameStatus, setNicknameStatus] = useState<{
    available: boolean | null;
    message: string;
  }>({ available: null, message: "" });
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const hasUserEditedNicknameRef = useRef(false);
  const lastGeneratedNameRef = useRef("");

  // Validar e limpar data de nascimento se for futura
  useEffect(() => {
    if (dateOfBirth) {
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      const birthDate = new Date(dateOfBirth);
      birthDate.setHours(0, 0, 0, 0);
      if (birthDate > today) {
        onDateOfBirthChange(null);
      }
    }
  }, [dateOfBirth, onDateOfBirthChange]);

  // Sincronizar nickname quando a prop mudar
  useEffect(() => {
    if (nickname) {
      setNicknameValue(nickname);
    }
  }, [nickname]);

  // Gerar nickname automático quando o nome mudar (apenas se nickname estiver vazio e usuário não editou)
  useEffect(() => {
    if (name && name.length >= 2 && !hasUserEditedNicknameRef.current) {
      // Se o nome mudou e ainda não geramos ou foi auto-gerado anteriormente
      if (name !== lastGeneratedNameRef.current) {
        if (!nicknameValue || isAutoGenerated) {
          const generated = generateNicknameFromName(name);
          setNicknameValue(generated);
          onNicknameChange(generated);
          setIsAutoGenerated(true);
          lastGeneratedNameRef.current = name;
        }
      }
    }
  }, [name, nicknameValue, isAutoGenerated, onNicknameChange]);

  // Debounce para verificar disponibilidade do nickname
  useEffect(() => {
    const timeoutId = setTimeout(async () => {
      const trimmedNickname = nicknameValue.trim();

      // Resetar status se vazio
      if (!trimmedNickname) {
        setNicknameStatus({ available: null, message: "" });
        setIsCheckingNickname(false);
        return;
      }

      // Validação básica de formato
      if (trimmedNickname.length < 3) {
        setNicknameStatus({
          available: false,
          message: t("validation.nicknameMin"),
        });
        setIsCheckingNickname(false);
        return;
      }

      if (trimmedNickname.length > 30) {
        setNicknameStatus({
          available: false,
          message: t("validation.nicknameMax"),
        });
        setIsCheckingNickname(false);
        return;
      }

      // Validar formato: apenas minúsculas, números e traços
      if (!/^[a-z0-9-]+$/.test(trimmedNickname)) {
        setNicknameStatus({
          available: false,
          message: t("validation.nicknameFormat"),
        });
        setIsCheckingNickname(false);
        return;
      }

      // Verificar disponibilidade
      setIsCheckingNickname(true);
      const result = await checkNicknameAvailability(trimmedNickname);
      setIsCheckingNickname(false);

      if (result.success) {
        if (result.available) {
          setNicknameStatus({
            available: true,
            message: t("validation.nicknameAvailable"),
          });
        } else {
          setNicknameStatus({
            available: false,
            message: t("validation.nicknameUnavailable"),
          });
        }
      } else {
        setNicknameStatus({
          available: false,
          message: result.error || t("validation.nicknameError"),
        });
      }
    }, 500); // Debounce de 500ms

    return () => clearTimeout(timeoutId);
  }, [nicknameValue]);

  const handleNicknameChange = (value: string) => {
    // Converter para minúsculas e permitir apenas letras, números e traços
    const normalized = value
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, "") // Remove caracteres inválidos
      .replace(/-+/g, "-") // Remove traços múltiplos
      .replace(/^-|-$/g, ""); // Remove traços no início/fim

    setNicknameValue(normalized);
    onNicknameChange(normalized);
    setIsAutoGenerated(false); // Marcar como editado manualmente
    hasUserEditedNicknameRef.current = true; // Marcar que usuário editou
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6 sm:space-y-8"
    >
      <OnboardStepHeader title={t("title")} description={t("description")} />

      <div className="mx-auto max-w-2xl space-y-4 py-4 sm:space-y-6">
        <div>
          <Label htmlFor="name" className="font-medium text-white">
            {t("fields.fullName")}
          </Label>
          <Input
            id="name"
            value={name}
            onChange={(e) => onNameChange(e.target.value)}
            placeholder={t("placeholders.name")}
            className="mt-2"
          />
          {autoFilledFields.name && (
            <p className="mt-1 text-xs text-white/60">
              {t("hints.autoFilledFromAccount")}
            </p>
          )}
        </div>

        <div>
          <Label htmlFor="nickname" className="font-medium text-white">
            {t("fields.nickname")}
          </Label>
          <div className="relative">
            <Input
              id="nickname"
              value={nicknameValue}
              onChange={(e) => handleNicknameChange(e.target.value)}
              placeholder={t("placeholders.nickname")}
              className="mt-2 pr-10"
              maxLength={30}
            />
            {nicknameValue && (
              <div className="absolute top-1/2 right-3 -translate-y-1/2">
                {isCheckingNickname ? (
                  <Loader2 className="h-4 w-4 animate-spin text-white/60" />
                ) : nicknameStatus.available === true ? (
                  <CheckCircle2 className="h-4 w-4 text-green-400" />
                ) : nicknameStatus.available === false ? (
                  <XCircle className="h-4 w-4 text-red-400" />
                ) : null}
              </div>
            )}
          </div>
          {nicknameValue && nicknameStatus.message && (
            <p
              className={`mt-1 text-xs ${
                nicknameStatus.available === true
                  ? "text-green-400"
                  : nicknameStatus.available === false
                    ? "text-red-400"
                    : "text-white/60"
              }`}
            >
              {nicknameStatus.message}
            </p>
          )}
          {!nicknameValue && (
            <p className="mt-1 text-xs text-white/60">
              {t("hints.nicknameInfo")}
            </p>
          )}
          {isAutoGenerated && nicknameValue && (
            <p className="mt-1 text-xs text-white/60">
              {t("hints.nicknameAutoGenerated")}
            </p>
          )}
        </div>

        <div>
          <Label htmlFor="email" className="font-medium text-white">
            {t("fields.email")}
          </Label>
          <Input
            id="email"
            type="email"
            value={email}
            onChange={(e) => {
              if (autoFilledFields.email) return;
              onEmailChange(e.target.value);
            }}
            placeholder={t("placeholders.email")}
            disabled={!!autoFilledFields.email}
            className="mt-2"
          />
          {autoFilledFields.email && (
            <p className="mt-1 text-xs text-white/60">
              {t("hints.autoFilledFromAccount")}
            </p>
          )}
        </div>

        <div>
          <Label htmlFor="dateOfBirth" className="font-medium text-white">
            {t("fields.dateOfBirth")}
          </Label>
          <DatePicker
            value={dateOfBirth}
            onChange={onDateOfBirthChange}
            className="mt-2"
            placeholder={t("placeholders.dateOfBirth")}
          />
          <p className="mt-1 text-xs text-white/60">
            {t("hints.dateOfBirthInfo")}
          </p>
        </div>

        <div>
          <Label htmlFor="nationality" className="font-medium text-white">
            {t("fields.nationality")}
          </Label>
          <div className="mt-2">
            <CountrySelector
              value={nationality}
              onValueChange={onNationalityChange}
              placeholder={t("placeholders.nationality")}
            />
          </div>
          <p className="mt-1 text-xs text-white/60">
            {t("hints.selectNationality")}
          </p>
        </div>

        <div className="space-y-4">
          <div>
            <h3 className="text-base font-medium text-white">
              {t("hints.locationHelp")}
            </h3>
          </div>
          <div className="grid grid-cols-1 gap-4 sm:gap-4 md:grid-cols-2">
            <div>
              <Label htmlFor="country" className="font-medium text-white">
                {t("fields.country")}
              </Label>
              <div className="mt-2">
                <CountrySelector
                  value={country}
                  onValueChange={onCountryChange}
                  placeholder={t("placeholders.country")}
                />
              </div>
            </div>

            <div>
              <Label htmlFor="city" className="font-medium text-white">
                {t("fields.city")}
              </Label>
              <Input
                id="city"
                value={city}
                onChange={(e) => onCityChange(e.target.value)}
                placeholder={t("placeholders.city")}
                className="mt-2"
              />
            </div>

            <div className="md:col-span-2">
              <Label htmlFor="location" className="font-medium text-white">
                {t("fields.location")}
              </Label>
              <Input
                id="location"
                value={location}
                onChange={(e) => onLocationChange(e.target.value)}
                placeholder={t("placeholders.location")}
                className="mt-2"
              />
              <p className="mt-1 text-xs text-white/60">
                {t("hints.locationOptional")}
              </p>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
