// Lista de países em português (sem duplicatas)
const countriesList = [
  { value: "PT", label: "Portugal" },
  { value: "BR", label: "Brasil" },
  { value: "AO", label: "Angola" },
  { value: "MZ", label: "Moçambique" },
  { value: "CV", label: "Cabo Verde" },
  { value: "GW", label: "Guiné-Bissau" },
  { value: "ST", label: "São Tomé e Príncipe" },
  { value: "ES", label: "Espanha" },
  { value: "FR", label: "França" },
  { value: "IT", label: "Itália" },
  { value: "DE", label: "Alemanha" },
  { value: "GB", label: "Reino Unido" },
  { value: "US", label: "Estados Unidos" },
  { value: "CA", label: "Canadá" },
  { value: "AR", label: "Argentina" },
  { value: "MX", label: "México" },
  { value: "CL", label: "Chile" },
  { value: "CO", label: "Colômbia" },
  { value: "PE", label: "Peru" },
  { value: "UY", label: "Uruguai" },
  { value: "VE", label: "Venezuela" },
  { value: "EC", label: "Equador" },
  { value: "PY", label: "Paraguai" },
  { value: "BO", label: "Bolívia" },
  { value: "CR", label: "Costa Rica" },
  { value: "PA", label: "Panamá" },
  { value: "GT", label: "Guatemala" },
  { value: "HN", label: "Honduras" },
  { value: "NI", label: "Nicarágua" },
  { value: "SV", label: "El Salvador" },
  { value: "DO", label: "República Dominicana" },
  { value: "CU", label: "Cuba" },
  { value: "JM", label: "Jamaica" },
  { value: "HT", label: "Haiti" },
  { value: "BE", label: "Bélgica" },
  { value: "NL", label: "Países Baixos" },
  { value: "CH", label: "Suíça" },
  { value: "AT", label: "Áustria" },
  { value: "SE", label: "Suécia" },
  { value: "NO", label: "Noruega" },
  { value: "DK", label: "Dinamarca" },
  { value: "FI", label: "Finlândia" },
  { value: "PL", label: "Polónia" },
  { value: "GR", label: "Grécia" },
  { value: "IE", label: "Irlanda" },
  { value: "CZ", label: "República Checa" },
  { value: "RO", label: "Roménia" },
  { value: "HU", label: "Hungria" },
  { value: "BG", label: "Bulgária" },
  { value: "HR", label: "Croácia" },
  { value: "SK", label: "Eslováquia" },
  { value: "SI", label: "Eslovénia" },
  { value: "LT", label: "Lituânia" },
  { value: "LV", label: "Letónia" },
  { value: "EE", label: "Estónia" },
  { value: "LU", label: "Luxemburgo" },
  { value: "MT", label: "Malta" },
  { value: "CY", label: "Chipre" },
  { value: "ZA", label: "África do Sul" },
  { value: "EG", label: "Egito" },
  { value: "MA", label: "Marrocos" },
  { value: "TN", label: "Tunísia" },
  { value: "DZ", label: "Argélia" },
  { value: "KE", label: "Quénia" },
  { value: "NG", label: "Nigéria" },
  { value: "GH", label: "Gana" },
  { value: "SN", label: "Senegal" },
  { value: "CI", label: "Costa do Marfim" },
  { value: "CM", label: "Camarões" },
  { value: "UG", label: "Uganda" },
  { value: "TZ", label: "Tanzânia" },
  { value: "ET", label: "Etiópia" },
  { value: "CN", label: "China" },
  { value: "JP", label: "Japão" },
  { value: "KR", label: "Coreia do Sul" },
  { value: "IN", label: "Índia" },
  { value: "ID", label: "Indonésia" },
  { value: "TH", label: "Tailândia" },
  { value: "VN", label: "Vietname" },
  { value: "PH", label: "Filipinas" },
  { value: "MY", label: "Malásia" },
  { value: "SG", label: "Singapura" },
  { value: "AU", label: "Austrália" },
  { value: "NZ", label: "Nova Zelândia" },
  { value: "RU", label: "Rússia" },
  { value: "TR", label: "Turquia" },
  { value: "SA", label: "Arábia Saudita" },
  { value: "AE", label: "Emirados Árabes Unidos" },
  { value: "IL", label: "Israel" },
  { value: "JO", label: "Jordânia" },
  { value: "LB", label: "Líbano" },
  { value: "IQ", label: "Iraque" },
  { value: "IR", label: "Irão" },
  { value: "PK", label: "Paquistão" },
  { value: "BD", label: "Bangladeche" },
  { value: "LK", label: "Sri Lanka" },
  { value: "MM", label: "Myanmar" },
  { value: "KH", label: "Camboja" },
  { value: "LA", label: "Laos" },
  { value: "BN", label: "Brunei" },
  { value: "AF", label: "Afeganistão" },
  { value: "BH", label: "Barém" },
  { value: "BT", label: "Butão" },
  { value: "TL", label: "Timor-Leste" },
  { value: "MV", label: "Maldivas" },
  { value: "MN", label: "Mongólia" },
  { value: "NP", label: "Nepal" },
  { value: "OM", label: "Omã" },
  { value: "QA", label: "Catar" },
  { value: "YE", label: "Iémen" },
  { value: "KG", label: "Quirguistão" },
  { value: "TJ", label: "Tajiquistão" },
  { value: "TM", label: "Turquemenistão" },
  { value: "UZ", label: "Usbequistão" },
  { value: "AM", label: "Arménia" },
  { value: "AZ", label: "Azerbaijão" },
  { value: "BY", label: "Bielorrússia" },
  { value: "BA", label: "Bósnia e Herzegovina" },
  { value: "GE", label: "Geórgia" },
  { value: "IS", label: "Islândia" },
  { value: "KZ", label: "Cazaquistão" },
  { value: "XK", label: "Kosovo" },
  { value: "MD", label: "Moldávia" },
  { value: "MC", label: "Mónaco" },
  { value: "ME", label: "Montenegro" },
  { value: "MK", label: "Macedónia do Norte" },
  { value: "SM", label: "San Marino" },
  { value: "RS", label: "Sérvia" },
  { value: "UA", label: "Ucrânia" },
  { value: "VA", label: "Vaticano" },
  { value: "AD", label: "Andorra" },
  { value: "AL", label: "Albânia" },
  { value: "KP", label: "Coreia do Norte" },
  { value: "KW", label: "Kuwait" },
  { value: "SY", label: "Síria" },
  { value: "TW", label: "Taiwan" },
];

// Remover duplicatas e ordenar
const uniqueCountries = Array.from(
  new Map(countriesList.map(item => [item.value, item])).values(),
);

export const COUNTRIES = uniqueCountries.sort((a, b) =>
  a.label.localeCompare(b.label, "pt"),
);
