export type EventStatus = "scheduled" | "confirmed" | "cancelled";

export type EventView = {
  id: number;
  teamId: number;
  title: string;
  description: string | null;
  type: string;
  location: string;
  city: string | null;
  country: string | null;
  startDate: Date;
  endDate: Date | null | undefined;
  gameStyle: string | null;
  experienceLevel: string | null;
  minAge: string | null;
  maxAge: string | null;
  gender: string | null;
  positionNeeded: string | null;
  participationCriteria: Record<string, unknown>;
  currentParticipants: string;
  maxParticipants: string | null;
  priceCents: number;
  currency: string;
  paymentRequired: boolean;
  paymentDeadlineHours: number | null;
  organizerId: string;
  organizer: string | null;
  language: string | null;
  images: string[];
  status: EventStatus;
  createdAt: Date;
  updatedAt: Date;
};
